### ISSUE TITLE
Meeting - Menentukan topik

### ISSUE THREAD

**Issue by ihsanularifinm** [ihsanularifinm/tugas_TKPPL_kelompok_9_MW-A_Pagi#3]
Silahkan pilih salah satu dari beberapa framework/library JS berikut ini:

1. Angular
2. Ionic
3. React
4. Vue
5. Svelte

**Comment by faizsitorus** [comment]
Sebaiknya kita bahas Vue karena itu pernah kita pelajari di semester sebelumnya

**Comment by usaljuntak14** [comment]
Oke sepakat
