### ISSUE TITLE
Topik yang dibahas, yaitu: Vue dan peembagian tugas

### ISSUE THREAD

**Issue by ihsanularifinm** [ihsanularifinm/tugas_TKPPL_kelompok_9_MW-A_Pagi#4]
Silahkan cari tahu mengenai Vue, terdiri dari kelebihan, kekurangan, dan performansi.
Pilih untuk masing-masing diri mana yang akan dibahas/dipresentasikan, lalu buatkan ke dalam slide reveal.js semenarik mungkin.

**Comment by YogieSinaga** [comment]
Aku akan bahas performansi Vue dan perbandingan Vue dengan framework/library yg lainnya

**Comment by ihsanularifinm** [comment]
Aku sendiri akan membahas sedikit mengenai apa itu Vue dan performansinya

**Comment by YogieSinaga** [comment]
Kalau begitu, aku akan bahas perbandingan Vue dengan framework Angular dan React

**Comment by usaljuntak14** [comment]
Aku akan bahas Kekurangan Vue

**Comment by usaljuntak14** [comment]
Yang berarti, Kelebihan Vue akan dibahas oleh @faizsitorus 😁
